# [QLThueVayCuoi]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [QLThueVayCuoi]    Script Date: 11/6/2023 05:06:25 PM ******/
CREATE DATABASE [QLThueVayCuoi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLThueVayCuoi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\QLThueVayCuoi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLThueVayCuoi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\QLThueVayCuoi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [QLThueVayCuoi] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLThueVayCuoi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLThueVayCuoi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QLThueVayCuoi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLThueVayCuoi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLThueVayCuoi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QLThueVayCuoi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLThueVayCuoi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QLThueVayCuoi] SET  MULTI_USER 
GO
ALTER DATABASE [QLThueVayCuoi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLThueVayCuoi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLThueVayCuoi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLThueVayCuoi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLThueVayCuoi] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLThueVayCuoi] SET QUERY_STORE = OFF
GO

# [dbo].[chitietphieuthue]

In [0]:
USE [QLThueVayCuoi]
GO

In [0]:
/****** Object:  Table [dbo].[chitietphieuthue]    Script Date: 11/6/2023 05:06:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[chitietphieuthue](
	[chitietphieuthue] [int] NOT NULL,
	[sophieu] [int] NULL,
	[masp] [int] NULL,
	[soluong] [int] NOT NULL,
	[hoadon] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[chitietphieuthue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[khachhang]

In [0]:
/****** Object:  Table [dbo].[khachhang]    Script Date: 11/6/2023 05:06:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[khachhang](
	[makh] [int] NOT NULL,
	[tenkh] [nvarchar](50) NOT NULL,
	[diachi] [nvarchar](200) NULL,
	[sodienthoai] [nvarchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[makh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[nhanvien]

In [0]:
/****** Object:  Table [dbo].[nhanvien]    Script Date: 11/6/2023 05:06:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[nhanvien](
	[manhanvien] [varchar](10) NOT NULL,
	[tennhanvien] [nvarchar](100) NULL,
	[ngaysinh] [date] NULL,
	[email] [nvarchar](100) NULL,
	[sodienthoainv] [varchar](15) NULL,
	[diachi] [nvarchar](200) NULL,
	[sodonhang] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[manhanvien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[sanphamthue]

In [0]:
/****** Object:  Table [dbo].[sanphamthue]    Script Date: 11/6/2023 05:06:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sanphamthue](
	[masp] [int] NOT NULL,
	[tensp] [nvarchar](100) NOT NULL,
	[nuocsx] [nvarchar](50) NULL,
	[tinhtrangsp] [nvarchar](100) NULL,
	[giavon] [int] NOT NULL,
	[giathue1ngay] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[masp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[thue]

In [0]:
/****** Object:  Table [dbo].[thue]    Script Date: 11/6/2023 05:06:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[thue](
	[sophieu] [int] NOT NULL,
	[makh] [int] NULL,
	[ngaychothue] [date] NOT NULL,
	[ngaytra] [date] NULL,
	[tientradutinh] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[sophieu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tknhanvien]

In [0]:
/****** Object:  Table [dbo].[tknhanvien]    Script Date: 11/6/2023 05:06:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tknhanvien](
	[manhanvien] [varchar](10) NOT NULL,
	[taikhoan] [nvarchar](100) NULL,
	[matkhau] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[manhanvien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [FK__chitietph__sophi__5535A963]

In [0]:
ALTER TABLE [dbo].[chitietphieuthue]  WITH CHECK ADD FOREIGN KEY([sophieu])
REFERENCES [dbo].[thue] ([sophieu])
GO

# [FK__chitietphi__masp__5629CD9C]

In [0]:
ALTER TABLE [dbo].[chitietphieuthue]  WITH CHECK ADD FOREIGN KEY([masp])
REFERENCES [dbo].[sanphamthue] ([masp])
GO

# [FK__nhanvien__manhan__4BAC3F29]

In [0]:
ALTER TABLE [dbo].[nhanvien]  WITH CHECK ADD FOREIGN KEY([manhanvien])
REFERENCES [dbo].[tknhanvien] ([manhanvien])
GO

# [FK__thue__makh__52593CB8]

In [0]:
ALTER TABLE [dbo].[thue]  WITH CHECK ADD FOREIGN KEY([makh])
REFERENCES [dbo].[khachhang] ([makh])
GO

# [QLThueVayCuoi]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [QLThueVayCuoi] SET  READ_WRITE 
GO